export const INITITATE_USER_LIST = "INITITATE_USER_LIST";
export const SUCCESS_USER_LIST = "SUCCESS_USER_LIST";
export const FAIL_USER_LIST = "FAIL_USER_LIST";

export const INITITATE_REGISTRATION = "INITITATE_REGISTRATION";
export const SUCCESS_REGISTRATION = "SUCCESS_REGISTRATION";
export const FAIL_REGISTRATION = "FAIL_REGISTRATION";

export const INITIATE_WIDGETS = "INITIATE_WIDGETS";
export const SUCCESS_WIDGETS = "SUCCESS_WIDGETS";
export const FAIL_WIDGETS = "FAIL_WIDGETS";

export const INITIATE_CREATE_DASHBOARD = "INITIATE_CREATE_DASHBOARD";
export const SUCCESS_CREATE_DASHBOARD = "SUCCESS_CREATE_DASHBOARD";
export const FAIL_CREATE_DASHBOARD = "FAIL_CREATE_DASHBOARD";

export const INITIATE_DASHBOARD_DETAIL = "INITIATE_DASHBOARD_DETAIL";
export const SUCCESS_DASHBOARD_DETAIL = "SUCCESS_DASHBOARD_DETAIL";
export const FAIL_DASHBOARD_DETAIL = "FAIL_DASHBOARD_DETAIL";
export const RESET_DASHBOARD_DETAIL = "RESET_DASHBOARD_DETAIL";

export const INITIATE_DASHBOARD_USER = "INITIATE_DASHBOARD_USER";
export const SUCCESS_DASHBOARD_USER = "SUCCESS_DASHBOARD_USER";
export const FAIL_DASHBOARD_USER = "FAIL_DASHBOARD_USER";

export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const GET_PROFILE = "GET_PROFILE";
export const PROFILE_ERROR = "PROFILE_ERROR";
export const CLEAR_PROFILE = "CLEAR_PROFILE";
export const PROFILE_UPDATED = "PROFILE_UPDATED";
export const REMOVE_EXPERIENCE = "REMOVE_EXPERIENCE";
export const REMOVE_EDUCATION = "REMOVE_EDUCATION";
export const DELETE_ACCOUNT = "DELETE_ACCOUNT";
export const GET_ALL_PROFILE = "GET_ALL_PROFILE";
export const CREATE_POST = "CREATE_POST";
export const DELETE_POST = "DELETE_POST";
export const GET_POSTS = "GET_POSTS";
export const POST_ERROR = "POST_ERROR";
export const UPDATE_LIKES = "UPDATE_LIKES";
export const GET_POST = "GET_POST";
export const ADD_COMMENT = "ADD_COMMENT";
export const REMOVE_COMMENT = "REMOVE_COMMENT";
export const PROFILE_CLEAR = "PROFILE_CLEAR";

export const INITITATE_USER_PROFILE_UPDATE = "INITITATE_USER_PROFILE_UPDATE";
export const SUCCESS_USER_PROFILE_UPDATE = "SUCCESS_USER_PROFILE_UPDATE";
export const FAIL_USER_PROFILE_UPDATE = "FAIL_USER_PROFILE_UPDATE";
